### ISSUE TITLE
flex-left

### ISSUE THREAD

**Issue by daniel-bergmann** [Basilcss/core#8]
flex-left class is not working

**Comment by Akash1965** [comment]
I am beginner. Can I try resolving your issue??

**Comment by daniel-bergmann** [comment]
@Akash1965 Hi there akash, you're welcome to make a pull request!

**Comment by Akash1965** [comment]
Hi I have made a pull request

**Comment by Akash1965** [comment]
Hi @daniel-bergmann  I have made a Pull Request

**Comment by daniel-bergmann** [comment]
@Akash1965 fantastic, i'll take a look tonight

**Comment by Akash1965** [comment]
@daniel-bergmann Thanks a lot
It was really a great experience to make my first PR
Actually at first by mistake I had added a few lines in the README.md file and had made a PR. Later I noticed the mistake and rectified it and committed the new change in the same PR (Sorry for the inconvience caused actually since this is my first time that's why I unknowingly made this mistake)

**Comment by daniel-bergmann** [comment]
Good job! Keep up the good work!
